# Production values for qalby-proxy
# This is a YAML-formatted file.
# Copy this file and customize it for your production deployment.

replicaCount: 2

image:
  repository: kamasalyamov/livellm-proxy
  pullPolicy: IfNotPresent
  tag: "dev-0.1.0"

# Use existing secret for API keys (recommended for production)
existingSecret: "qalby-proxy-secrets"

# Configuration
config:
  # DO NOT put real API keys here in production
  # Use existingSecret or Kubernetes secrets management instead
  masterApiKey: ""  # Will be loaded from secret
  host: "0.0.0.0"
  port: 8000
  
  providers:
    - kind: openai
      name: openai
      apiKey: ""  # Will be loaded from secret
      baseUrl: "https://api.proxyapi.ru/openai/v1"
    - kind: google
      name: google
      apiKey: ""  # Will be loaded from secret
      baseUrl: "https://api.proxyapi.ru/google"
    - kind: elevenlabs
      name: elevenlabs
      apiKey: ""  # Will be loaded from secret
      baseUrl: "http://5.253.189.83:29999"
  
  fallback:
    transcribeModel: "openai/whisper-1"
    speakModel: "openai/tts-1"
    chatModel: "google/gemini-2.5-flash"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

# Enable ingress for external access
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - host: qalby-proxy.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: qalby-proxy-tls
      hosts:
        - qalby-proxy.example.com

# Resource limits for production
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

# Health checks
livenessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 10
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Enable autoscaling
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Security context
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  fsGroup: 1000

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false

# Node selector for production nodes
nodeSelector: {}
  # environment: production

# Tolerations for production taints
tolerations: []

# Affinity rules for high availability
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - qalby-proxy
          topologyKey: kubernetes.io/hostname

