

master_api_key: sk-123
host: 0.0.0.0
port: 8000

providers:
  - kind: openai
    name: openai
    api_key: sk-...
    base_url: https://.../v1
  - kind: openai
    name: vllm
    api_key: sk-...
    base_url: https://.../v1
  - kind: google
    name: google
    api_key: sk-...
    base_url: https://...
  - kind: elevenlabs
    name: elevenlabs
    api_key: sk_...
    base_url: http://...:29999