{{- if and (not .Values.existingSecret) (or .Values.secrets.masterApiKey .Values.secrets.openaiApiKey .Values.secrets.googleApiKey .Values.secrets.elevenlabsApiKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-secrets
  labels:
    {{- include "chart.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.masterApiKey }}
  masterApiKey: {{ .Values.secrets.masterApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  openaiApiKey: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.googleApiKey }}
  googleApiKey: {{ .Values.secrets.googleApiKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.elevenlabsApiKey }}
  elevenlabsApiKey: {{ .Values.secrets.elevenlabsApiKey | b64enc | quote }}
  {{- end }}
{{- end }}

